version: "3.9"
services:
  db:
    ports:
      - 5432:5432
    env_file:
      - local.env
  backend:
    command: bash -c "npm run start:dev"
    ports:
      - 4000:4000
    volumes:
      - .:/app
    env_file:
      - local.env
  migrate:
    image: node:16-bullseye
    command: bash -c "npm run migrate:dev"
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - local.env