version: "3.9"
services:
  db:
    ports:
      - 5432:5432
    env_file:
      - ./local.env
  backend:
    command: bash -c "npm run start:dev"
    ports:
      - 4000:4000
    volumes:
      - .:/app
    env_file:
      - ./local.env
  migrate:
    volumes:
      - .:/app
    env_file:
      - ./local.env