version: "3.9"
services:
  db:
    image: postgres:12
    restart: always
    ports:
      - 5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
    - xpndr-db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    user: node
    command: npm start
    restart: unless-stopped
    build:
      context: .
    ports:
      - 4000
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV
      - PORT
      - JWT_SECRET
      - JWT_ALGORITHM
      - JWT_EXPIRES_IN
      - POSTGRES_URL

  migrate:
    user: node
    image: xpndr_backend
    command: bash -c "npm run migrate:dev"
    environment:
      - POSTGRES_URL
  
volumes:
  xpndr-db-data: