# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test and Build (Server)

on:
  push:
    paths:
      - 'server/**'
  pull_request:
    paths:
      - 'server/**'

jobs:
  install-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Enter directory
        run: |
          cd server
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm ci
      - name: Run tests
        run: |
          npm test
        env:
          CI: true